spring:
  datasource:
    url: jdbc:mysql://www.zcscloud.net:3306/new_technology
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zhuohcunnodatabase
    hikari:
      connection-timeout: 30000  # 连接池获取连接的超时时间
      maximum-pool-size: 10      # 最大连接池大小
      minimum-idle: 5           # 最小空闲连接数
      idle-timeout: 600000      # 空闲连接最大存活时间
      max-lifetime: 1800000     # 连接最大生命周期
      pool-name: HikariCP       # 连接池名称

  data:
    redis:
      port: 6379
      host: www.zcscloud.net
      password: Zhuohcunnodatabase

  neo4j:
    uri: neo4j+s://bc465d3f.databases.neo4j.io:7687
    authentication:
      username: neo4j
      password: 5OhCg0wm2dqBimphafyXm3Huy76t2vr663gU-r9dvJw
  cache:
    type: redis
  task:
    execution:
      pool:
        core-size: 5          # 核心线程数
        max-size: 10          # 最大线程数
        queue-capacity: 25     # 队列容量
        keep-alive: 60s       # 线程空闲时间
  security:
    user:
      name: admin
      password: admin
logging:
  level:
    com.zaxxer.hikari: DEBUG


server:
  port: 8089

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true   # 开启 MyBatis 二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL输出日志
